/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActionToBundle
 */
export interface ActionToBundle {
    /**
     * Protocol to interact with
     * @type {string}
     * @memberof ActionToBundle
     */
    'protocol': string;
    /**
     * 
     * @type {string}
     * @memberof ActionToBundle
     */
    'action': ActionToBundleActionEnum;
    /**
     * 
     * @type {object}
     * @memberof ActionToBundle
     */
    'args': object;
}

export const ActionToBundleActionEnum = {
    Approve: 'approve',
    Borrow: 'borrow',
    Bridge: 'bridge',
    Deposit: 'deposit',
    Singledeposit: 'singledeposit',
    Multideposit: 'multideposit',
    Tokenizedsingledeposit: 'tokenizedsingledeposit',
    Tokenizedmultideposit: 'tokenizedmultideposit',
    Multioutsingledeposit: 'multioutsingledeposit',
    Depositclmm: 'depositclmm',
    Harvest: 'harvest',
    Permittransferfrom: 'permittransferfrom',
    Redeem: 'redeem',
    Singleredeem: 'singleredeem',
    Multiredeem: 'multiredeem',
    Tokenizedsingleredeem: 'tokenizedsingleredeem',
    Tokenizedmultiredeem: 'tokenizedmultiredeem',
    Redeemclmm: 'redeemclmm',
    Repay: 'repay',
    Swap: 'swap',
    Transfer: 'transfer',
    Transferfrom: 'transferfrom',
    Route: 'route',
    Call: 'call',
    Split: 'split',
    Merge: 'merge',
    Balance: 'balance',
    Minamountout: 'minamountout',
    Slippage: 'slippage',
    Fee: 'fee',
    Ensofee: 'ensofee'
} as const;

export type ActionToBundleActionEnum = typeof ActionToBundleActionEnum[keyof typeof ActionToBundleActionEnum];


