/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Hop
 */
export interface Hop {
    /**
     * 
     * @type {Array<string>}
     * @memberof Hop
     */
    'tokenIn': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Hop
     */
    'tokenOut': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Hop
     */
    'protocol': string;
    /**
     * 
     * @type {string}
     * @memberof Hop
     */
    'action': string;
    /**
     * 
     * @type {string}
     * @memberof Hop
     */
    'primary': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Hop
     */
    'internalRoutes': Array<string>;
    /**
     * 
     * @type {object}
     * @memberof Hop
     */
    'args': object;
    /**
     * 
     * @type {number}
     * @memberof Hop
     */
    'chainId'?: number;
}

