/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IporShortcutInput
 */
export interface IporShortcutInput {
    /**
     * Flag that indicates whether to use the shared router
     * @type {boolean}
     * @memberof IporShortcutInput
     */
    'isRouter'?: boolean | null;
    /**
     * Amount of tokenIn in wei
     * @type {string}
     * @memberof IporShortcutInput
     */
    'amountIn': string;
    /**
     * Address of the tokenIn. For ETH, use 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
     * @type {string}
     * @memberof IporShortcutInput
     */
    'tokenIn': string;
    /**
     * Address of the tokenBToBuy
     * @type {string}
     * @memberof IporShortcutInput
     */
    'tokenBToBuy': string;
    /**
     * Percentage of tokenB to buy in basis points (1/10000)
     * @type {string}
     * @memberof IporShortcutInput
     */
    'percentageForTokenB': string;
    /**
     * Slippage in basis points (1/10000). Default is 300
     * @type {string}
     * @memberof IporShortcutInput
     */
    'slippage'?: string;
    /**
     * Flag that indicates whether to simulate the transaction, verify some assertions, return simulationURL and events
     * @type {boolean}
     * @memberof IporShortcutInput
     */
    'simulate'?: boolean | null;
}

