/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TokenModel } from './token-model';

/**
 * 
 * @export
 * @interface NonTokenizedModel
 */
export interface NonTokenizedModel {
    /**
     * Chain ID of the network of the nontokenized position
     * @type {number}
     * @memberof NonTokenizedModel
     */
    'chainId': number;
    /**
     * The specific standard integration or version of the nontokenized position
     * @type {string}
     * @memberof NonTokenizedModel
     */
    'protocol': string;
    /**
     * Ethereum address of the nontokenized position
     * @type {string}
     * @memberof NonTokenizedModel
     */
    'address': string;
    /**
     * Ethereum address of the nontokenized position
     * @type {string}
     * @memberof NonTokenizedModel
     */
    'primaryAddress': string;
    /**
     * Underlying tokens of nontokenized position
     * @type {Array<TokenModel>}
     * @memberof NonTokenizedModel
     */
    'underlyingTokens': Array<TokenModel> | null;
}

