/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * Total amount of pages
     * @type {number}
     * @memberof PaginationMeta
     */
    'total': number;
    /**
     * Last page number
     * @type {number}
     * @memberof PaginationMeta
     */
    'lastPage': number;
    /**
     * Current page number
     * @type {number}
     * @memberof PaginationMeta
     */
    'currentPage': number;
    /**
     * Amount of elements per page
     * @type {number}
     * @memberof PaginationMeta
     */
    'perPage': number;
    /**
     * Previous page
     * @type {number}
     * @memberof PaginationMeta
     */
    'prev': number;
    /**
     * Next page
     * @type {number}
     * @memberof PaginationMeta
     */
    'next': number;
    /**
     * Cursor for pagination
     * @type {number}
     * @memberof PaginationMeta
     */
    'cursor': number;
}

