/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TokenModel } from './token-model';

/**
 * 
 * @export
 * @interface PositionModel
 */
export interface PositionModel {
    /**
     * Ethereum address of the token
     * @type {string}
     * @memberof PositionModel
     */
    'address': string;
    /**
     * Chain ID of the network of the token
     * @type {number}
     * @memberof PositionModel
     */
    'chainId': number;
    /**
     * Type of token
     * @type {string}
     * @memberof PositionModel
     */
    'type': string;
    /**
     * Token decimals
     * @type {number}
     * @memberof PositionModel
     */
    'decimals': number;
    /**
     * Token name
     * @type {string}
     * @memberof PositionModel
     */
    'symbol': string | null;
    /**
     * Token symbol
     * @type {string}
     * @memberof PositionModel
     */
    'name': string | null;
    /**
     * A list of logos for the token
     * @type {Array<string>}
     * @memberof PositionModel
     */
    'logosUri': Array<string> | null;
    /**
     * Underlying tokens of defi token
     * @type {Array<TokenModel>}
     * @memberof PositionModel
     */
    'underlyingTokens': Array<TokenModel> | null;
    /**
     * The overarching project or platform associated with the DeFi token
     * @type {string}
     * @memberof PositionModel
     */
    'project': string | null;
    /**
     * The specific standard integration or version of the DeFi project
     * @type {string}
     * @memberof PositionModel
     */
    'protocolSlug': string | null;
    /**
     * The defi position APY
     * @type {number}
     * @memberof PositionModel
     */
    'apy': number | null;
    /**
     * The defi position base APY
     * @type {number}
     * @memberof PositionModel
     */
    'apyBase': number | null;
    /**
     * The defi position reward APY
     * @type {number}
     * @memberof PositionModel
     */
    'apyReward': number | null;
    /**
     * The defi position TVL
     * @type {number}
     * @memberof PositionModel
     */
    'tvl': number | null;
    /**
     * Ethereum address for contract interaction of defi token
     * @type {string}
     * @memberof PositionModel
     */
    'primaryAddress': string | null;
}

