/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Hop } from './hop';
// May contain unused imports in some cases
// @ts-ignore
import type { Transaction } from './transaction';

/**
 * 
 * @export
 * @interface RouteShortcutTransaction
 */
export interface RouteShortcutTransaction {
    /**
     * 
     * @type {string}
     * @memberof RouteShortcutTransaction
     */
    'gas': string;
    /**
     * 
     * @type {string}
     * @memberof RouteShortcutTransaction
     */
    'amountOut': string;
    /**
     * Price impact in basis points, null if USD price not found
     * @type {number}
     * @memberof RouteShortcutTransaction
     */
    'priceImpact': number;
    /**
     * An array of the fee amount collected for each tokenIn
     * @type {Array<string>}
     * @memberof RouteShortcutTransaction
     */
    'feeAmount': Array<string>;
    /**
     * Block number the transaction was created on
     * @type {number}
     * @memberof RouteShortcutTransaction
     */
    'createdAt': number;
    /**
     * The tx object to use in `ethers`
     * @type {Transaction}
     * @memberof RouteShortcutTransaction
     */
    'tx': Transaction;
    /**
     * The route the shortcut will use
     * @type {Array<Hop>}
     * @memberof RouteShortcutTransaction
     */
    'route': Array<Hop>;
}

