/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TokenModel
 */
export interface TokenModel {
    /**
     * Ethereum address of the token
     * @type {string}
     * @memberof TokenModel
     */
    'address': string;
    /**
     * Chain ID of the network of the token
     * @type {number}
     * @memberof TokenModel
     */
    'chainId': number;
    /**
     * Type of token
     * @type {string}
     * @memberof TokenModel
     */
    'type': string;
    /**
     * Token decimals
     * @type {number}
     * @memberof TokenModel
     */
    'decimals': number;
    /**
     * Token name
     * @type {string}
     * @memberof TokenModel
     */
    'symbol': string | null;
    /**
     * Token symbol
     * @type {string}
     * @memberof TokenModel
     */
    'name': string | null;
    /**
     * A list of logos for the token
     * @type {Array<string>}
     * @memberof TokenModel
     */
    'logosUri': Array<string> | null;
}

