/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WalletBalance
 */
export interface WalletBalance {
    /**
     * The address of the token
     * @type {string}
     * @memberof WalletBalance
     */
    'token': string;
    /**
     * The unformatted balance of the token
     * @type {string}
     * @memberof WalletBalance
     */
    'amount': string;
    /**
     * The unformatted balance of the token
     * @type {number}
     * @memberof WalletBalance
     */
    'decimals': number;
    /**
     * Price of the token in usd
     * @type {string}
     * @memberof WalletBalance
     */
    'price': string;
    /**
     * Name of the token
     * @type {string}
     * @memberof WalletBalance
     */
    'name': string;
    /**
     * Symbol of the token
     * @type {string}
     * @memberof WalletBalance
     */
    'symbol': string;
    /**
     * Logo of the token
     * @type {string}
     * @memberof WalletBalance
     */
    'logoUri': string;
}

