/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WalletApproveTransaction
 */
export interface WalletApproveTransaction {
    /**
     * The tx object to use in `ethers`
     * @type {object}
     * @memberof WalletApproveTransaction
     */
    'tx': object;
    /**
     * The gas estimate for the transaction
     * @type {string}
     * @memberof WalletApproveTransaction
     */
    'gas': string;
    /**
     * The token address to approve
     * @type {string}
     * @memberof WalletApproveTransaction
     */
    'token': string;
    /**
     * The amount of tokens to approve
     * @type {string}
     * @memberof WalletApproveTransaction
     */
    'amount': string;
    /**
     * The spender address to approve
     * @type {string}
     * @memberof WalletApproveTransaction
     */
    'spender': string;
}

