/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { NonTokenizedModel } from './NonTokenizedModel';
import {
    NonTokenizedModelFromJSON,
    NonTokenizedModelFromJSONTyped,
    NonTokenizedModelToJSON,
    NonTokenizedModelToJSONTyped,
} from './NonTokenizedModel';

/**
 * 
 * @export
 * @interface NonTokenizedControllerTokens200Response
 */
export interface NonTokenizedControllerTokens200Response {
    /**
     * Metadata for pagination
     * @type {PaginationMeta}
     * @memberof NonTokenizedControllerTokens200Response
     */
    meta: PaginationMeta;
    /**
     * Returned data for current page
     * @type {Array<NonTokenizedModel>}
     * @memberof NonTokenizedControllerTokens200Response
     */
    data?: Array<NonTokenizedModel>;
}

/**
 * Check if a given object implements the NonTokenizedControllerTokens200Response interface.
 */
export function instanceOfNonTokenizedControllerTokens200Response(value: object): value is NonTokenizedControllerTokens200Response {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function NonTokenizedControllerTokens200ResponseFromJSON(json: any): NonTokenizedControllerTokens200Response {
    return NonTokenizedControllerTokens200ResponseFromJSONTyped(json, false);
}

export function NonTokenizedControllerTokens200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NonTokenizedControllerTokens200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': PaginationMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(NonTokenizedModelFromJSON)),
    };
}

export function NonTokenizedControllerTokens200ResponseToJSON(json: any): NonTokenizedControllerTokens200Response {
    return NonTokenizedControllerTokens200ResponseToJSONTyped(json, false);
}

export function NonTokenizedControllerTokens200ResponseToJSONTyped(value?: NonTokenizedControllerTokens200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PaginationMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(NonTokenizedModelToJSON)),
    };
}

