/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface PaginatedResult
 */
export interface PaginatedResult {
    /**
     * Metadata for pagination
     * @type {PaginationMeta}
     * @memberof PaginatedResult
     */
    meta: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedResult interface.
 */
export function instanceOfPaginatedResult(value: object): value is PaginatedResult {
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function PaginatedResultFromJSON(json: any): PaginatedResult {
    return PaginatedResultFromJSONTyped(json, false);
}

export function PaginatedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': PaginationMetaFromJSON(json['meta']),
    };
}

export function PaginatedResultToJSON(json: any): PaginatedResult {
    return PaginatedResultToJSONTyped(json, false);
}

export function PaginatedResultToJSONTyped(value?: PaginatedResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

