/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * Total amount of pages
     * @type {number}
     * @memberof PaginationMeta
     */
    total: number;
    /**
     * Last page number
     * @type {number}
     * @memberof PaginationMeta
     */
    lastPage: number;
    /**
     * Current page number
     * @type {number}
     * @memberof PaginationMeta
     */
    currentPage: number;
    /**
     * Amount of elements per page
     * @type {number}
     * @memberof PaginationMeta
     */
    perPage: number;
    /**
     * Previous page
     * @type {number}
     * @memberof PaginationMeta
     */
    prev: number;
    /**
     * Next page
     * @type {number}
     * @memberof PaginationMeta
     */
    next: number;
    /**
     * Cursor for pagination
     * @type {number}
     * @memberof PaginationMeta
     */
    cursor: number;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): value is PaginationMeta {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('lastPage' in value) || value['lastPage'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    if (!('prev' in value) || value['prev'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('cursor' in value) || value['cursor'] === undefined) return false;
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'lastPage': json['lastPage'],
        'currentPage': json['currentPage'],
        'perPage': json['perPage'],
        'prev': json['prev'],
        'next': json['next'],
        'cursor': json['cursor'],
    };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
    return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(value?: PaginationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'lastPage': value['lastPage'],
        'currentPage': value['currentPage'],
        'perPage': value['perPage'],
        'prev': value['prev'],
        'next': value['next'],
        'cursor': value['cursor'],
    };
}

