/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
    NetworkToJSONTyped,
} from './Network';

/**
 * 
 * @export
 * @interface ProtocolModel
 */
export interface ProtocolModel {
    /**
     * 
     * @type {string}
     * @memberof ProtocolModel
     */
    project: string;
    /**
     * 
     * @type {string}
     * @memberof ProtocolModel
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ProtocolModel
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProtocolModel
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProtocolModel
     */
    url: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProtocolModel
     */
    logosUri: Array<string> | null;
    /**
     * 
     * @type {Array<Network>}
     * @memberof ProtocolModel
     */
    chains: Array<Network> | null;
}

/**
 * Check if a given object implements the ProtocolModel interface.
 */
export function instanceOfProtocolModel(value: object): value is ProtocolModel {
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('logosUri' in value) || value['logosUri'] === undefined) return false;
    if (!('chains' in value) || value['chains'] === undefined) return false;
    return true;
}

export function ProtocolModelFromJSON(json: any): ProtocolModel {
    return ProtocolModelFromJSONTyped(json, false);
}

export function ProtocolModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProtocolModel {
    if (json == null) {
        return json;
    }
    return {
        
        'project': json['project'],
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'],
        'url': json['url'],
        'logosUri': json['logosUri'] == null ? null : json['logosUri'],
        'chains': (json['chains'] == null ? null : (json['chains'] as Array<any>).map(NetworkFromJSON)),
    };
}

export function ProtocolModelToJSON(json: any): ProtocolModel {
    return ProtocolModelToJSONTyped(json, false);
}

export function ProtocolModelToJSONTyped(value?: ProtocolModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project': value['project'],
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'url': value['url'],
        'logosUri': value['logosUri'],
        'chains': (value['chains'] == null ? null : (value['chains'] as Array<any>).map(NetworkToJSON)),
    };
}

