/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenModel
 */
export interface TokenModel {
    /**
     * Ethereum address of the token
     * @type {string}
     * @memberof TokenModel
     */
    address: string;
    /**
     * Chain ID of the network of the token
     * @type {number}
     * @memberof TokenModel
     */
    chainId: number;
    /**
     * Type of token
     * @type {string}
     * @memberof TokenModel
     */
    type: string;
    /**
     * Token decimals
     * @type {number}
     * @memberof TokenModel
     */
    decimals: number;
    /**
     * Token name
     * @type {string}
     * @memberof TokenModel
     */
    symbol: string | null;
    /**
     * Token symbol
     * @type {string}
     * @memberof TokenModel
     */
    name: string | null;
    /**
     * A list of logos for the token
     * @type {Array<string>}
     * @memberof TokenModel
     */
    logosUri: Array<string> | null;
}

/**
 * Check if a given object implements the TokenModel interface.
 */
export function instanceOfTokenModel(value: object): value is TokenModel {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('logosUri' in value) || value['logosUri'] === undefined) return false;
    return true;
}

export function TokenModelFromJSON(json: any): TokenModel {
    return TokenModelFromJSONTyped(json, false);
}

export function TokenModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenModel {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'chainId': json['chainId'],
        'type': json['type'],
        'decimals': json['decimals'],
        'symbol': json['symbol'],
        'name': json['name'],
        'logosUri': json['logosUri'] == null ? null : json['logosUri'],
    };
}

export function TokenModelToJSON(json: any): TokenModel {
    return TokenModelToJSONTyped(json, false);
}

export function TokenModelToJSONTyped(value?: TokenModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'chainId': value['chainId'],
        'type': value['type'],
        'decimals': value['decimals'],
        'symbol': value['symbol'],
        'name': value['name'],
        'logosUri': value['logosUri'],
    };
}

