/* tslint:disable */
/* eslint-disable */
/**
 * 
 * #### Enso API - Find detailed documentation on [docs.enso.finance](https://docs.enso.finance). - To use the API, **you must include your API Key in the Authorization header** (Bearer format). - For testing, Swagger pre-authorizes you using the key: `1e02632d-6feb-4a75-a157-documentation` (1rps). - Get your own API Key at [enso.finance/developers](https://enso.finance/developers).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletBalance
 */
export interface WalletBalance {
    /**
     * The address of the token
     * @type {string}
     * @memberof WalletBalance
     */
    token: string;
    /**
     * The unformatted balance of the token
     * @type {string}
     * @memberof WalletBalance
     */
    amount: string;
    /**
     * The unformatted balance of the token
     * @type {number}
     * @memberof WalletBalance
     */
    decimals: number;
    /**
     * Price of the token in usd
     * @type {string}
     * @memberof WalletBalance
     */
    price: string;
    /**
     * Name of the token
     * @type {string}
     * @memberof WalletBalance
     */
    name: string;
    /**
     * Symbol of the token
     * @type {string}
     * @memberof WalletBalance
     */
    symbol: string;
    /**
     * Logo of the token
     * @type {string}
     * @memberof WalletBalance
     */
    logoUri: string;
}

/**
 * Check if a given object implements the WalletBalance interface.
 */
export function instanceOfWalletBalance(value: object): value is WalletBalance {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('logoUri' in value) || value['logoUri'] === undefined) return false;
    return true;
}

export function WalletBalanceFromJSON(json: any): WalletBalance {
    return WalletBalanceFromJSONTyped(json, false);
}

export function WalletBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletBalance {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'amount': json['amount'],
        'decimals': json['decimals'],
        'price': json['price'],
        'name': json['name'],
        'symbol': json['symbol'],
        'logoUri': json['logoUri'],
    };
}

export function WalletBalanceToJSON(json: any): WalletBalance {
    return WalletBalanceToJSONTyped(json, false);
}

export function WalletBalanceToJSONTyped(value?: WalletBalance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'amount': value['amount'],
        'decimals': value['decimals'],
        'price': value['price'],
        'name': value['name'],
        'symbol': value['symbol'],
        'logoUri': value['logoUri'],
    };
}

